//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coding
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPayment
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string payment_status { get; set; }
        public Nullable<int> userid { get; set; }
    
        public virtual tblUser tblUser { get; set; }
    }
}
